name: BDD Tests

on:
  push:
    branches:
      - main     
  pull_request:
    branches:
      - main      

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres            
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y gcc libpq-dev
          apt-get install -y curl wget python3-selenium
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Run the server locally
        run: |
          echo "\n*** CREATING TEST DB ***\n"
          curl -X PUT postgresql://postgres:postgres@postgres:5432/postgres
          echo "\n*** STARTING APPLICATION ***\n"
          gunicorn --log-level=critical --bind=0.0.0.0:8000 service:app &
          sleep 5
          curl -I http://localhost:8000/
          echo "\n*** SERVER IS RUNNING ***"
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          FLASK_APP: service:app
          FLASK_ENV: development
          GUNICORN_BIND: "0.0.0.0:8000"
          DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres

      - name: Run behavior driven development tests with behave
        run: behave